---
stages:
  - build
  - package

build:
  image: golang:latest
  stage: build
  variables:
    GOFLAGS: '-mod=vendor'
    GOOS: 'linux'
  script:
    - go test -v -cover -timeout 60s -parallel 5 -race ./...
    - CGO_ENABLED=0 go build -a -ldflags "-extldflags '-static'" -o check_sssd_backend_status .
  artifacts:
    expire_in: '1 hour'
    paths:
      - check_sssd_backend_status

package:
  image: gitlab-registry.in2p3.fr/cc-in2p3/docker-fpm:latest
  stage: package
  script:
    - mkdir -p usr/lib64/nagios/plugins/
    - install -m 0755 check_sssd_backend_status usr/lib64/nagios/plugins/check_sssd_backend_status
    - fpm -s dir -t rpm --license "CECILL-B" --no-rpm-autoreqprov --depends "sssd-tools" -n "nagios-plugin-sssd-backend-status" -v "$(git describe --always --tags HEAD | sed 's/^v//')" --url "${CI_PROJECT_URL}" --description "Nagios plugins that checks sssd backend status" --maintainer "Remi Ferrand <remi.ferrand@cc.in2p3.fr>" ./usr
  dependencies:
    - build
  artifacts:
    expire_in: '1 hour'
    paths:
      - "*.rpm"
